name = "THM Forever Server Mods"
author = "ArcOnyx"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "575cdabdba81ff8fd21f8d7286fc9b26ddabe80cb171d3b186a0a97bc3c4824c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
