name = "THM Forever Server Mods"
author = "ArcOnyx"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ec5f5942bfbae7c55ffee0325e14fc819cf5aa4854e169423404088c9273fa2"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
