name = "THM Forever Server Mods"
author = "ArcOnyx"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40ecd61a840ce61e77b318a28aa587d2b71e9924845724ee845a6fc8cad7cc6e"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
