# This is a basic workflow to help you get started with Actions

name: Packwiz refresh

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Nix Quick Install
        uses: nixbuild/nix-quick-install-action@v30

      - name: Run packwiz refresh
        run: nix develop --command packwiz refresh

      - name: Commit any changes
        run: |
            if [[ `git status --porcelain` ]]; then
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add -u
              git commit -m "packwiz refresh"
              git push
            else
              echo "No changes"
            fi
      
